### ISSUE TITLE
[ERROR] Error saving Super Table fields throwing HTTP 400: Post request required

### ISSUE THREAD

**Issue by ogamacheInk** [benjamminf/craft-quick-field#18] opened 2022-11-24 18:08 UTC
# Description
Gets a 400 Post request required when saving a Super table field.
# How to reproduce the error
1. Use CraftCMS 4
2. Install Quick fields plugin
3. Install Super table plugin
4. Create Section
5. Create a Super table field in with Quick field
6. Save -> Get error in console (POST 400)

# System Info
## Application Info
**PHP version:** 8.0.24
**OS version:** Linux 5.10.16.3-microsoft-standard-WSL2 & Linux 5.10.124-linuxkit
**Database driver & version:** MySQL 10.4.26
**Image driver & version:** Imagick 3.6.0 (ImageMagick 6.9.11-60)
**Craft edition & version:** Craft Pro 4.3.3
**Yii version:** 2.0.46
**Twig version:** v3.4.3
**Guzzle version:** 7.5.0

## Plugins
Amazon S3 2.0.1
Amazon SES 2.0.1
Button Box 4.1.0
Feed Me 5.0.4
Field Manager 3.0.4
Navigation 2.0.13
Quick Field 2.0.2
Redactor 3.0.2
Smith 2.0.0
Sprig 2.3.0
Super Table 3.0.5
Typed link field 2.1.4

**Comment by ttempleton** [comment] 2022-11-25 00:54
This seems to be working for me - could you please post more details of the Super Table field you're trying to create, e.g. settings and subfields?

**Comment by ttempleton** [comment] 2022-12-08 13:38
I'll close this issue as not reproducible for now, but if the issue persists for you, please let me know (including providing the previously requested information) and I'll reopen it.

**Comment by ogamacheInk** [comment] 2022-12-08 17:59
Hi there, I am so sorry for the delay.

The super table can be completely empty and it still does not work. Ill check a little more on it.

Thank you again!

**Closed as completed** 2023-10-16 09:28 UTC
Labels: bug

**Comment by ttempleton** [comment] 2023-10-16 09:33
I think this should be fixed now in 2.0.7 (turned out to specifically affect single-site installs, see #22) but please let me know if the error persists.
