### ISSUE TITLE
Creating a multi-select only allows 1 option to be added.

### ISSUE THREAD

**Issue by admench** [benjamminf/craft-quick-field#10] opened 2016-07-21 15:46 UTC
Creating a multi-select only allows 1 option to be added.

I have to go into craft/settings/fields to add more options, when pressing the button '+ Add an option' nothing happens.

Thanks!

**Comment by benjamminf** [comment] 2016-07-24 00:42
Hey @admench thanks for the report.

I'm trying this now and can't seem to reproduce the issue. After clicking on the `+ Add an option` button, can you check the console for errors?

**Comment by roydigerhund** [comment] 2016-08-24 13:35
Hey, 

I have the same error in Safari, Chrome and FF. I'm using Craft 2.6.2911 and Quickfield 0.3.3 together with Neo (1.3.4) and Reasons (1.0.6). 

There is no console log when I hit the button. 

The problem only shows up inside Neo, but not when I edit a section.

Your Plugin Reaseons does have the same problem inside Neo. If I want to combine a conditional with an dropdown with more than one option, it only shows the first one.

**Comment by benjamminf** [comment] 2016-08-25 10:16
@roydigerhund You're right, I'm experiencing the same issue when used with Neo. Now that I can reproduce the issue I'll look into it ASAP 👍

**Comment by ttempleton** [comment] 2022-06-30 02:40
Closing this issue due to having been fixed in version 0.3.4.

**Closed as completed by ttempleton** 2022-06-30 02:40 UTC
Labels: bug
